### ISSUE TITLE
plugin stack traces contain double frames

### ISSUE THREAD

**Issue by fdrozdowski** [delphix/virtualization-sdk#50]
I noticed that in all my error messages, my stack traces show double frames for anything within the plugin:

Traceback (most recent call last):
  File "__pyclasspath__/dlpx/virtualization/platform/_plugin.py", line 947, in _internal_configure
  File "/home/delphix/docker-plugin/src/plugin.py", line 52, in vdb_configure
  File "/home/delphix/docker-plugin/src/plugin.py", line 52, in vdb_configure
  File "/home/delphix/docker-plugin/src/provisioning.py", line 161, in configure
  File "/home/delphix/docker-plugin/src/provisioning.py", line 161, in configure
  File "/home/delphix/docker-plugin/src/provisioning.py", line 89, in configure_container
  File "/home/delphix/docker-plugin/src/provisioning.py", line 89, in configure_container
  File "/home/delphix/docker-plugin/src/util.py", line 77, in read_json
  File "/home/delphix/docker-plugin/src/util.py", line 77, in read_json
  File "/var/tmp/webapps/resources/WEB-INF/lib/jython-standalone-2.7.1.jar/Lib/json/__init__.py", line 338, in loads
  File "/var/tmp/webapps/resources/WEB-INF/lib/jython-standalone-2.7.1.jar/Lib/json/decoder.py", line 365, in decode

Also, it really shouldn't be showing information about the environment where I built it (/home/delphix/docker-plugin).

┆Issue is synchronized with this [Jira Bug](https://jira.delphix.com/browse/PYT-550) by [Unito](https://www.unito.io/learn-more)

**Comment by fdrozdowski** [comment]
➤ Grant Magdanz commented:

In addition to the double stack frames, the stack traces also contain file paths that reflect the paths where the file existed at build time. This is both for our internal Python code as well as plugin authors' code. I believe these paths are captured when we compile Python files and are stored in the .pyc files. We need to look into this more, confirm, the issue, and figure out what we can do to workaround it. The paths are confusing and embarrassing.

**Comment by fdrozdowski** [comment]
➤ Muralidhar Nimmagadda commented:

The absolute paths issue is resolved by PYT-386 but the double stack frames issue is till there. It is coming from the jython exception. we need more investigation.
