### ISSUE TITLE
dvp init hitting TypeError on Windows10

### ISSUE THREAD

**Issue by AleksandrLiber** [delphix/virtualization-sdk#96]
This is being hit with nightly regression runs:
http://regression.jenkins.delphix.com/job/dlpx-app-gate/job/5.3/job/release/job/regression-tests/job/virtualization_sdk/job/PYTHON_STAGED_LINUX73_SDK_WINDOWS10/7/testReport/junit/blackbox.virtualization_sdk.sdk/positive/test_dvp_init_all_flags/

the sdk version is 1.0.0 from artifactory

```18:48:05  SSHError: : Error executing command "C:\Users\dtully\AppData\Roaming\Python\Scripts\dvp init -n "blackbox_plugin" -r "C:\Users\dtully\blackbox_plugin" -s "STAGED"". Code: 1. Error: Traceback (most recent call last):
18:48:05    File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
18:48:05      "__main__", fname, loader, pkg_name)
18:48:05    File "c:\python27\lib\runpy.py", line 72, in _run_code
18:48:05      exec code in run_globals
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Scripts\dvp.exe\__main__.py", line 9, in <module>
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 829, in __call__
18:48:05      return self.main(*args, **kwargs)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 782, in main
18:48:05      rv = self.invoke(ctx)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 1257, in invoke
18:48:05      sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 700, in make_context
18:48:05      self.parse_args(ctx, args)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 1048, in parse_args
18:48:05      value, args = param.handle_parse_result(ctx, opts, args)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 1623, in handle_parse_result
18:48:05      value = self.full_process_value(ctx, value)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 1965, in full_process_value
18:48:05      return Parameter.full_process_value(self, ctx, value)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 1589, in full_process_value
18:48:05      value = self.process_value(ctx, value)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 1579, in process_value
18:48:05      return self.type_cast_value(ctx, value)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 1568, in type_cast_value
18:48:05      return _convert(value, (self.nargs != 1) + bool(self.multiple))
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\core.py", line 1565, in _convert
18:48:05      return self.type(value, self, ctx)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\types.py", line 46, in __call__
18:48:05      return self.convert(value, param, ctx)
18:48:05    File "C:\Users\dtully\AppData\Roaming\Python\Python27\site-packages\click\types.py", line 187, in convert
18:48:05      normed_value = lower(normed_value)
18:48:05  TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'
18:48:05  .
18:48:05  Command output:

**Comment by muralinimmagadda** [comment]
This bug is introduced in click 7.1 onwards : https://github.com/pallets/click/blob/7.1/src/click/types.py. 

This file is not available in 7.0. So, the workaround is to uninstall 7.1 and install 7.0m version of click in the virtual environment.
